### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by mikemahoney218** [stac-api-extensions/filter#21]
Hi all! The following links in README.md currently return 404 (list generated via https://github.com/tcort/markdown-link-check):

  [✖] http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter → Status: 404
  [✖] http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/cql2-text → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/cql2-json → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2 → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/basic-spatial-operators → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/spatial-operators → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/temporal-operators → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/functions → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/arithmetic → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/array-operators → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/property-property → Status: 404
  [✖] http://www.opengis.net/spec/cql2/1.0/conf/accent-case-insensitive-comparison → Status: 404
  [✖] https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql → Status: 404
  [✖] https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.bnf → Status: 404
  [✖] https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.json → Status: 404
  [✖] https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.yml → Status: 404
  [✖] https://github.com/xbib/cql → Status: 404

**Comment by philvarner** [comment]
Thanks @mikemahoney218

**Comment by philvarner** [comment]
https://xbib.org/xbib/cql
